build(hook): run biome lint only if client code has changed

diff --git a/.husky/_/pre-commit b/.husky/_/pre-commit
--- a/.husky/_/pre-commit
+++ b/.husky/_/pre-commit
@@ -1,17 +1,21 @@
 #!/usr/bin/env sh
 
-cd client
-bin_path=$(which bun)
-bin_name="bun"
+FILES=$(git diff --cached --name-only)
 
-if [ -n "$bin_path" ]; then
-  bun run lint
-else 
-  bin_name="npm"
-  npm run lint
-fi
+if echo "$FILES" | grep -q "^client/"; then
+  cd client
+  bin_path=$(which bun)
+  bin_name="bun"
 
-if [ $? -ne 0 ]; then
-  echo "You can run \"$bin_name run lint:write\" to fix some errors!"
-  exit 1
+  if [ -n "$bin_path" ]; then
+    bun run lint
+  else 
+    bin_name="npm"
+    npm run lint
+  fi
+
+  if [ $? -ne 0 ]; then
+    echo "You can run \"$bin_name run lint:write\" to fix some errors!"
+    exit 1
+  fi
 fi
